theme: jekyll-theme-hacker
title: gitificial's blog
author: gitificial
permalink: pretty
github_username: gitificial
header_pages:
 - index.md
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
